### ISSUE TITLE
whois : command not found

### ISSUE THREAD

**Issue by delta0800** [UN5T48L3/ranger#1]
Hello, 

i got the below error.  Generated .lst is empty.

AS200502 <-- added to list
ranger.sh: line 10: whois: command not found
AS48363 <-- added to list
ranger.sh: line 10: whois: command not found
AS47582 <-- added to list
ranger.sh: line 10: whois: command not found
AS42080 <-- added to list
ranger.sh: line 10: whois: command not found
AS2599 <-- added to list
ranger.sh: line 10: whois: command not found
AS48158 <-- added to list
ranger.sh: line 10: whois: command not found
AS3276 <-- added to list
ranger.sh: line 10: whois: command not found
AS203526 <-- added to list

**Comment by UN5T48L3** [comment]
# `yum install jwhois`
OR
# `yum install whois`

**Comment by delta0800** [comment]
Hi, 
Noted with thanks. 
Good tools you have built.
