### ISSUE TITLE
Are we gonna talk abt how i caught your ass lacking

### ISSUE THREAD

**Issue by urmommy-c** [UN5T48L3/ranger#3]
<img width="322" alt="skid" src="https://user-images.githubusercontent.com/64172367/171804900-6b0b2045-d7f5-4b32-b1b1-80f9ed556b6b.png">
<img width="452" alt="skid2" src="https://user-images.githubusercontent.com/64172367/171804981-98449259-b48f-455f-a5ce-4dc3414fbbfc.png">
<img width="555" alt="skid3" src="https://user-images.githubusercontent.com/64172367/171805124-c3875587-8488-4e80-a4f1-902c0dd20285.png">

**Comment by UN5T48L3** [comment]
you are too stupid because at least missing about 3 years, lmao.
